version: '3.9'

services:
  postgres:
    container_name: taxfill-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=taxfill
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres